-- ============================================================================
-- CAMPUS RELAY - SUPABASE SCHEMA
-- ============================================================================
--
-- WHAT THIS IS
--   The complete database schema for a Campus Relay deployment on Supabase:
--   every table, constraint, index, the append-only triggers, row-level
--   security, and the storage bucket that backs attachments.
--
-- SOURCE OF TRUTH
--   SQLAlchemy models (backend/app/models) own the shape; Alembic owns the
--   migration history. The table DDL below is GENERATED by
--   `python -m scripts.export_supabase_schema`. Treat the generated section as
--   read-only: change a model, re-run the generator, and commit the result.
--
-- HOW TO USE IT
--   Option A - Supabase dashboard: Database -> SQL Editor -> New query, paste
--              this whole file, Run.
--   Option B - psql:  psql "$DATABASE_URL" -f supabase/schema.sql
--   Option C - let Alembic do it:  cd backend && alembic upgrade head
--              (equivalent for the table DDL; it will not create the storage
--              bucket or the RLS statements, so run this file too if you want
--              those)
--
-- CONNECTION NOTE
--   The API connects as a privileged Postgres role (see DATABASE_URL). RLS is
--   enabled defensively so that a leaked anon/service key cannot read campus
--   data through PostgREST - there are deliberately NO permissive policies.
--   All access is mediated by the API, never by the browser.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. Extensions
-- ---------------------------------------------------------------------------
-- Only pgcrypto is needed beyond the Postgres defaults: `gen_random_uuid()` is
-- used by Supabase tooling, and JSONB is built in.
create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- 2. Schema
-- ---------------------------------------------------------------------------
-- Everything lives in `public`, which is what PostgREST exposes and what the
-- API's search_path resolves to.

CREATE TABLE campuses (
	name VARCHAR(160) NOT NULL, 
	code VARCHAR(32) NOT NULL, 
	city VARCHAR(80), 
	state VARCHAR(80), 
	timezone VARCHAR(64) NOT NULL, 
	default_language VARCHAR(8) NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (code)
);

CREATE TABLE permissions (
	key VARCHAR(64) NOT NULL, 
	category VARCHAR(40) NOT NULL, 
	description VARCHAR(240), 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (key)
);

CREATE TABLE roles (
	key VARCHAR(32) NOT NULL, 
	name VARCHAR(80) NOT NULL, 
	description VARCHAR(240), 
	is_system BOOLEAN NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_roles_key CHECK (key IN ('SUPER_ADMIN', 'ADMIN', 'WARDEN', 'DEPARTMENT_HEAD', 'STAFF', 'SECURITY', 'HELPDESK_OPERATOR', 'STUDENT')), 
	UNIQUE (key)
);

CREATE TABLE batches (
	campus_id INTEGER NOT NULL, 
	name VARCHAR(40) NOT NULL, 
	start_year INTEGER NOT NULL, 
	end_year INTEGER NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_batch_campus_name UNIQUE (campus_id, name), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE
);

CREATE INDEX ix_batches_campus_id ON batches (campus_id);

CREATE TABLE departments (
	campus_id INTEGER NOT NULL, 
	name VARCHAR(120) NOT NULL, 
	code VARCHAR(32) NOT NULL, 
	kind VARCHAR(32) NOT NULL, 
	head_user_id INTEGER, 
	sla_multiplier FLOAT NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_department_campus_code UNIQUE (campus_id, code), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE
);

CREATE INDEX ix_departments_campus_id ON departments (campus_id);

CREATE TABLE policies (
	campus_id INTEGER NOT NULL, 
	key VARCHAR(64) NOT NULL, 
	name VARCHAR(160) NOT NULL, 
	description TEXT, 
	service_key VARCHAR(48), 
	effect VARCHAR(16) NOT NULL, 
	evaluation_order INTEGER NOT NULL, 
	conditions JSONB NOT NULL, 
	message VARCHAR(300) NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_policy_campus_key UNIQUE (campus_id, key), 
	CONSTRAINT ck_effect CHECK (effect IN ('ALLOW', 'DENY', 'REQUIRE')), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE
);

CREATE INDEX ix_policies_campus_id ON policies (campus_id);

CREATE INDEX ix_policies_campus_service ON policies (campus_id, service_key);

CREATE TABLE role_permissions (
	role_id INTEGER NOT NULL, 
	permission_id INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (role_id, permission_id), 
	FOREIGN KEY(role_id) REFERENCES roles (id) ON DELETE CASCADE, 
	FOREIGN KEY(permission_id) REFERENCES permissions (id) ON DELETE CASCADE
);

CREATE TABLE sla_rules (
	campus_id INTEGER NOT NULL, 
	service_key VARCHAR(48), 
	priority VARCHAR(16) NOT NULL, 
	target_minutes INTEGER NOT NULL, 
	at_risk_ratio FLOAT NOT NULL, 
	escalate_to_role VARCHAR(32) NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_sla_rule_scope UNIQUE (campus_id, service_key, priority), 
	CONSTRAINT ck_sla_rules_priority CHECK (priority IN ('LOW', 'NORMAL', 'HIGH', 'CRITICAL', 'URGENT')), 
	CONSTRAINT ck_sla_rules_escalate_role CHECK (escalate_to_role IN ('SUPER_ADMIN', 'ADMIN', 'WARDEN', 'DEPARTMENT_HEAD', 'STAFF', 'SECURITY', 'HELPDESK_OPERATOR', 'STUDENT')), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE
);

CREATE INDEX ix_sla_rules_campus_id ON sla_rules (campus_id);

CREATE TABLE users (
	campus_id INTEGER NOT NULL, 
	role_id INTEGER NOT NULL, 
	email VARCHAR(180) NOT NULL, 
	full_name VARCHAR(160) NOT NULL, 
	password_hash VARCHAR(255) NOT NULL, 
	phone VARCHAR(24), 
	telegram_chat_id VARCHAR(64), 
	whatsapp_number VARCHAR(24), 
	language VARCHAR(8) NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	must_change_password BOOLEAN NOT NULL, 
	last_login_at TIMESTAMP WITH TIME ZONE, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_user_campus_email UNIQUE (campus_id, email), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(role_id) REFERENCES roles (id) ON DELETE RESTRICT
);

CREATE INDEX ix_users_campus_id ON users (campus_id);

CREATE INDEX ix_users_campus_role ON users (campus_id, role_id);

CREATE INDEX ix_users_role_id ON users (role_id);

CREATE TABLE workflows (
	campus_id INTEGER NOT NULL, 
	key VARCHAR(48) NOT NULL, 
	name VARCHAR(120) NOT NULL, 
	description TEXT, 
	initial_state VARCHAR(32) NOT NULL, 
	allowed_states JSONB NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_workflow_campus_key UNIQUE (campus_id, key), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE
);

CREATE INDEX ix_workflows_campus_id ON workflows (campus_id);

CREATE TABLE years (
	campus_id INTEGER NOT NULL, 
	name VARCHAR(40) NOT NULL, 
	ordinal INTEGER NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_year_campus_name UNIQUE (campus_id, name), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE
);

CREATE INDEX ix_years_campus_id ON years (campus_id);

CREATE TABLE branches (
	campus_id INTEGER NOT NULL, 
	department_id INTEGER, 
	name VARCHAR(120) NOT NULL, 
	code VARCHAR(24) NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_branch_campus_code UNIQUE (campus_id, code), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(department_id) REFERENCES departments (id) ON DELETE SET NULL
);

CREATE INDEX ix_branches_campus_id ON branches (campus_id);

CREATE INDEX ix_branches_department_id ON branches (department_id);

CREATE TABLE devices (
	campus_id INTEGER NOT NULL, 
	user_id INTEGER NOT NULL, 
	device_uid VARCHAR(80) NOT NULL, 
	platform VARCHAR(40) NOT NULL, 
	user_agent VARCHAR(300), 
	push_subscription JSONB, 
	last_seen_at TIMESTAMP WITH TIME ZONE, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_device_user_uid UNIQUE (user_id, device_uid), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_devices_campus_id ON devices (campus_id);

CREATE TABLE hostels (
	campus_id INTEGER NOT NULL, 
	name VARCHAR(120) NOT NULL, 
	code VARCHAR(24) NOT NULL, 
	gender VARCHAR(12) NOT NULL, 
	warden_user_id INTEGER, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_hostel_campus_code UNIQUE (campus_id, code), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(warden_user_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_hostels_campus_id ON hostels (campus_id);

CREATE TABLE notices (
	campus_id INTEGER NOT NULL, 
	title VARCHAR(200) NOT NULL, 
	content TEXT NOT NULL, 
	summary VARCHAR(300), 
	notice_type VARCHAR(16) NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	priority VARCHAR(16) NOT NULL, 
	category VARCHAR(48) NOT NULL, 
	created_by_id INTEGER, 
	publish_at TIMESTAMP WITH TIME ZONE, 
	expires_at TIMESTAMP WITH TIME ZONE, 
	published_at TIMESTAMP WITH TIME ZONE, 
	archived_at TIMESTAMP WITH TIME ZONE, 
	is_pinned BOOLEAN NOT NULL, 
	acknowledgement_required BOOLEAN NOT NULL, 
	required_action VARCHAR(24), 
	required_action_label VARCHAR(80), 
	attachment_path VARCHAR(400), 
	attachment_name VARCHAR(240), 
	image_path VARCHAR(400), 
	share_token VARCHAR(64), 
	share_enabled BOOLEAN NOT NULL, 
	audience_summary VARCHAR(240), 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_notices_type CHECK (notice_type IN ('NORMAL', 'IMPORTANT', 'URGENT', 'EMERGENCY')), 
	CONSTRAINT ck_notices_status CHECK (status IN ('DRAFT', 'SCHEDULED', 'PUBLISHED', 'EXPIRED', 'ARCHIVED')), 
	CONSTRAINT ck_notices_priority CHECK (priority IN ('LOW', 'NORMAL', 'HIGH', 'CRITICAL', 'URGENT')), 
	CONSTRAINT ck_notices_required_action CHECK (required_action IN ('READ', 'ACKNOWLEDGE', 'SUBMIT_FORM', 'VIEW_DOCUMENT', 'REGISTER', 'OPEN_CASE', 'VIEW_TIMETABLE')), 
	CONSTRAINT uq_notices_share_token UNIQUE (share_token), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(created_by_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_notices_campus_id ON notices (campus_id);

CREATE INDEX ix_notices_campus_status ON notices (campus_id, status, publish_at);

CREATE TABLE notification_preferences (
	campus_id INTEGER NOT NULL, 
	user_id INTEGER NOT NULL, 
	category VARCHAR(32) NOT NULL, 
	in_app BOOLEAN NOT NULL, 
	push BOOLEAN NOT NULL, 
	telegram BOOLEAN NOT NULL, 
	whatsapp BOOLEAN NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_notification_pref_user_category UNIQUE (user_id, category), 
	CONSTRAINT ck_notification_prefs_category CHECK (category IN ('CASE_UPDATE', 'APPROVAL', 'CERTIFICATE_READY', 'LEAVE_STATUS', 'GATE_PASS', 'TIMETABLE', 'NOTICE', 'URGENT_ANNOUNCEMENT', 'SLA_ALERT', 'SYSTEM', 'MESS', 'ACADEMIC', 'HOSTEL')), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_notification_preferences_campus_id ON notification_preferences (campus_id);

CREATE TABLE services (
	campus_id INTEGER NOT NULL, 
	workflow_id INTEGER, 
	department_id INTEGER, 
	key VARCHAR(48) NOT NULL, 
	name VARCHAR(120) NOT NULL, 
	description TEXT, 
	category VARCHAR(24) NOT NULL, 
	icon VARCHAR(32) NOT NULL, 
	default_priority VARCHAR(16) NOT NULL, 
	default_sla_minutes INTEGER NOT NULL, 
	allowed_requester_roles JSONB NOT NULL, 
	form_schema JSONB NOT NULL, 
	requires_attachment BOOLEAN NOT NULL, 
	allow_anonymous_location BOOLEAN NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	sort_order INTEGER NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_service_campus_key UNIQUE (campus_id, key), 
	CONSTRAINT ck_category CHECK (category IN ('HOSTEL', 'FACILITY', 'ACADEMIC', 'ADMINISTRATIVE', 'FINANCE', 'MESS', 'SECURITY', 'OTHER')), 
	CONSTRAINT ck_services_priority CHECK (default_priority IN ('LOW', 'NORMAL', 'HIGH', 'CRITICAL', 'URGENT')), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(workflow_id) REFERENCES workflows (id) ON DELETE SET NULL, 
	FOREIGN KEY(department_id) REFERENCES departments (id) ON DELETE SET NULL
);

CREATE INDEX ix_services_campus_id ON services (campus_id);

CREATE TABLE staff (
	campus_id INTEGER NOT NULL, 
	user_id INTEGER NOT NULL, 
	department_id INTEGER, 
	designation VARCHAR(80) NOT NULL, 
	employee_code VARCHAR(32), 
	skills JSONB NOT NULL, 
	workload_capacity INTEGER NOT NULL, 
	is_available BOOLEAN NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_staff_user UNIQUE (user_id), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	FOREIGN KEY(department_id) REFERENCES departments (id) ON DELETE SET NULL
);

CREATE INDEX ix_staff_campus_id ON staff (campus_id);

CREATE INDEX ix_staff_department_id ON staff (department_id);

CREATE TABLE sync_operations (
	campus_id INTEGER NOT NULL, 
	user_id INTEGER NOT NULL, 
	device_id VARCHAR(80), 
	idempotency_key VARCHAR(80) NOT NULL, 
	operation VARCHAR(24) NOT NULL, 
	entity_type VARCHAR(32) NOT NULL, 
	entity_id VARCHAR(64), 
	status VARCHAR(24) NOT NULL, 
	attempts INTEGER NOT NULL, 
	source_channel VARCHAR(24) NOT NULL, 
	payload JSONB NOT NULL, 
	client_base JSONB NOT NULL, 
	response JSONB NOT NULL, 
	last_error TEXT, 
	captured_offline_at TIMESTAMP WITH TIME ZONE, 
	synced_at TIMESTAMP WITH TIME ZONE, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_sync_operations_idempotency UNIQUE (idempotency_key), 
	CONSTRAINT ck_sync_operations_operation CHECK (operation IN ('CASE_CREATE', 'CASE_COMMENT', 'CASE_STATUS', 'CASE_VERIFY', 'NOTICE_READ', 'NOTICE_ACTION', 'NOTIFICATION_READ', 'GATE_LOG')), 
	CONSTRAINT ck_sync_operations_status CHECK (status IN ('QUEUED', 'SYNCING', 'SYNCED', 'FAILED_RETRYING', 'CONFLICT', 'FAILED_REQUIRES_ACTION')), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_sync_operations_campus_id ON sync_operations (campus_id);

CREATE INDEX ix_sync_operations_status ON sync_operations (status, updated_at);

CREATE INDEX ix_sync_operations_user_device ON sync_operations (user_id, device_id, created_at);

CREATE TABLE workflow_steps (
	workflow_id INTEGER NOT NULL, 
	order_index INTEGER NOT NULL, 
	key VARCHAR(48) NOT NULL, 
	name VARCHAR(120) NOT NULL, 
	step_type VARCHAR(24) NOT NULL, 
	responsible_role VARCHAR(32), 
	sla_minutes INTEGER, 
	requires_note BOOLEAN NOT NULL, 
	instructions TEXT, 
	transitions JSONB NOT NULL, 
	required_fields JSONB NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_workflow_step_key UNIQUE (workflow_id, key), 
	CONSTRAINT ck_step_type CHECK (step_type IN ('APPROVAL', 'ASSIGNMENT', 'ACTION', 'RESOLUTION', 'VERIFICATION', 'NOTIFICATION')), 
	CONSTRAINT ck_workflow_steps_role CHECK (responsible_role IN ('SUPER_ADMIN', 'ADMIN', 'WARDEN', 'DEPARTMENT_HEAD', 'STAFF', 'SECURITY', 'HELPDESK_OPERATOR', 'STUDENT')), 
	FOREIGN KEY(workflow_id) REFERENCES workflows (id) ON DELETE CASCADE
);

CREATE INDEX ix_workflow_steps_workflow_id ON workflow_steps (workflow_id);

CREATE TABLE blocks (
	campus_id INTEGER NOT NULL, 
	hostel_id INTEGER NOT NULL, 
	name VARCHAR(80) NOT NULL, 
	code VARCHAR(16) NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_block_hostel_code UNIQUE (hostel_id, code), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(hostel_id) REFERENCES hostels (id) ON DELETE CASCADE
);

CREATE INDEX ix_blocks_campus_id ON blocks (campus_id);

CREATE INDEX ix_blocks_hostel_id ON blocks (hostel_id);

CREATE TABLE notice_reads (
	campus_id INTEGER NOT NULL, 
	notice_id INTEGER NOT NULL, 
	user_id INTEGER NOT NULL, 
	state VARCHAR(20) NOT NULL, 
	delivered_at TIMESTAMP WITH TIME ZONE, 
	read_at TIMESTAMP WITH TIME ZONE, 
	acknowledged_at TIMESTAMP WITH TIME ZONE, 
	action_completed_at TIMESTAMP WITH TIME ZONE, 
	source_channel VARCHAR(24) NOT NULL, 
	device_id VARCHAR(80), 
	offline_captured_at TIMESTAMP WITH TIME ZONE, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_notice_read_user UNIQUE (notice_id, user_id), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(notice_id) REFERENCES notices (id) ON DELETE CASCADE, 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_notice_reads_campus_id ON notice_reads (campus_id);

CREATE INDEX ix_notice_reads_notice_state ON notice_reads (notice_id, state);

CREATE INDEX ix_notice_reads_user ON notice_reads (user_id, created_at);

CREATE TABLE notice_shares (
	campus_id INTEGER NOT NULL, 
	notice_id INTEGER NOT NULL, 
	shared_by_id INTEGER, 
	channel VARCHAR(24) NOT NULL, 
	token VARCHAR(64) NOT NULL, 
	view_count INTEGER NOT NULL, 
	last_viewed_at TIMESTAMP WITH TIME ZONE, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_notice_share_token UNIQUE (token), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(notice_id) REFERENCES notices (id) ON DELETE CASCADE, 
	FOREIGN KEY(shared_by_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_notice_shares_campus_id ON notice_shares (campus_id);

CREATE TABLE notice_targets (
	notice_id INTEGER NOT NULL, 
	target_type VARCHAR(16) NOT NULL, 
	target_id INTEGER, 
	target_value VARCHAR(64), 
	include BOOLEAN NOT NULL, 
	label VARCHAR(120), 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_notice_targets_type CHECK (target_type IN ('CAMPUS', 'DEPARTMENT', 'BRANCH', 'YEAR', 'BATCH', 'HOSTEL', 'BLOCK', 'ROLE', 'USER')), 
	CONSTRAINT uq_notice_target_unique UNIQUE (notice_id, target_type, target_id), 
	FOREIGN KEY(notice_id) REFERENCES notices (id) ON DELETE CASCADE
);

CREATE INDEX ix_notice_targets_lookup ON notice_targets (target_type, target_id);

CREATE INDEX ix_notice_targets_notice ON notice_targets (notice_id);

CREATE TABLE rooms (
	campus_id INTEGER NOT NULL, 
	hostel_id INTEGER NOT NULL, 
	block_id INTEGER NOT NULL, 
	number VARCHAR(16) NOT NULL, 
	floor INTEGER NOT NULL, 
	capacity INTEGER NOT NULL, 
	occupant_count INTEGER NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_room_block_number UNIQUE (block_id, number), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(hostel_id) REFERENCES hostels (id) ON DELETE CASCADE, 
	FOREIGN KEY(block_id) REFERENCES blocks (id) ON DELETE CASCADE
);

CREATE INDEX ix_rooms_block_id ON rooms (block_id);

CREATE INDEX ix_rooms_campus_id ON rooms (campus_id);

CREATE INDEX ix_rooms_hostel_id ON rooms (hostel_id);

CREATE TABLE locations (
	campus_id INTEGER NOT NULL, 
	code VARCHAR(48) NOT NULL, 
	name VARCHAR(160) NOT NULL, 
	kind VARCHAR(24) NOT NULL, 
	building VARCHAR(80), 
	hostel_id INTEGER, 
	block_id INTEGER, 
	room_id INTEGER, 
	department_id INTEGER, 
	parent_id INTEGER, 
	qr_enabled BOOLEAN NOT NULL, 
	is_active BOOLEAN NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_location_campus_code UNIQUE (campus_id, code), 
	CONSTRAINT ck_kind CHECK (kind IN ('HOSTEL_ROOM', 'WASHROOM', 'WATER_COOLER', 'CORRIDOR', 'CLASSROOM', 'LAB', 'LIBRARY', 'MESS', 'GATE', 'OFFICE', 'EQUIPMENT', 'OTHER')), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(hostel_id) REFERENCES hostels (id) ON DELETE SET NULL, 
	FOREIGN KEY(block_id) REFERENCES blocks (id) ON DELETE SET NULL, 
	FOREIGN KEY(room_id) REFERENCES rooms (id) ON DELETE SET NULL, 
	FOREIGN KEY(department_id) REFERENCES departments (id) ON DELETE SET NULL, 
	FOREIGN KEY(parent_id) REFERENCES locations (id) ON DELETE SET NULL
);

CREATE INDEX ix_locations_campus_id ON locations (campus_id);

CREATE INDEX ix_locations_campus_kind ON locations (campus_id, kind);

CREATE TABLE students (
	campus_id INTEGER NOT NULL, 
	user_id INTEGER, 
	roll_number VARCHAR(32) NOT NULL, 
	registration_number VARCHAR(48), 
	full_name VARCHAR(160) NOT NULL, 
	branch_id INTEGER, 
	year_id INTEGER, 
	batch_id INTEGER, 
	hostel_id INTEGER, 
	room_id INTEGER, 
	is_hosteller BOOLEAN NOT NULL, 
	guardian_phone VARCHAR(24), 
	dues_amount INTEGER NOT NULL, 
	dues_paid INTEGER NOT NULL, 
	has_smartphone BOOLEAN NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_student_campus_roll UNIQUE (campus_id, roll_number), 
	CONSTRAINT uq_student_user UNIQUE (user_id), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	FOREIGN KEY(branch_id) REFERENCES branches (id) ON DELETE SET NULL, 
	FOREIGN KEY(year_id) REFERENCES years (id) ON DELETE SET NULL, 
	FOREIGN KEY(batch_id) REFERENCES batches (id) ON DELETE SET NULL, 
	FOREIGN KEY(hostel_id) REFERENCES hostels (id) ON DELETE SET NULL, 
	FOREIGN KEY(room_id) REFERENCES rooms (id) ON DELETE SET NULL
);

CREATE INDEX ix_students_campus_id ON students (campus_id);

CREATE TABLE assets (
	campus_id INTEGER NOT NULL, 
	code VARCHAR(48) NOT NULL, 
	name VARCHAR(160) NOT NULL, 
	category VARCHAR(48) NOT NULL, 
	location_id INTEGER, 
	department_id INTEGER, 
	state VARCHAR(24) NOT NULL, 
	installed_at TIMESTAMP WITH TIME ZONE, 
	notes TEXT, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_asset_campus_code UNIQUE (campus_id, code), 
	CONSTRAINT ck_state CHECK (state IN ('OPERATIONAL', 'DEGRADED', 'UNDER_REPAIR', 'OUT_OF_SERVICE', 'RETIRED')), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(location_id) REFERENCES locations (id) ON DELETE SET NULL, 
	FOREIGN KEY(department_id) REFERENCES departments (id) ON DELETE SET NULL
);

CREATE INDEX ix_assets_campus_id ON assets (campus_id);

CREATE INDEX ix_assets_campus_location ON assets (campus_id, location_id);

CREATE INDEX ix_assets_location_id ON assets (location_id);

CREATE TABLE cases (
	campus_id INTEGER NOT NULL, 
	case_number VARCHAR(24) NOT NULL, 
	requester_id INTEGER, 
	requester_role VARCHAR(32) NOT NULL, 
	requester_student_id INTEGER, 
	created_by_id INTEGER, 
	service_id INTEGER, 
	service_key VARCHAR(48) NOT NULL, 
	category VARCHAR(48) NOT NULL, 
	subcategory VARCHAR(64), 
	title VARCHAR(200) NOT NULL, 
	description TEXT NOT NULL, 
	location_id INTEGER, 
	asset_id INTEGER, 
	department_id INTEGER, 
	assigned_staff_id INTEGER, 
	priority VARCHAR(16) NOT NULL, 
	status VARCHAR(32) NOT NULL, 
	current_step_key VARCHAR(48), 
	source_channel VARCHAR(24) NOT NULL, 
	language VARCHAR(8) NOT NULL, 
	sla_minutes INTEGER, 
	due_at TIMESTAMP WITH TIME ZONE, 
	sla_state VARCHAR(16) NOT NULL, 
	first_response_at TIMESTAMP WITH TIME ZONE, 
	breached_at TIMESTAMP WITH TIME ZONE, 
	at_risk_notified_at TIMESTAMP WITH TIME ZONE, 
	escalation_level INTEGER NOT NULL, 
	required_approvals JSONB NOT NULL, 
	state_payload JSONB NOT NULL, 
	verification_state VARCHAR(20) NOT NULL, 
	resolution_note TEXT, 
	resolved_at TIMESTAMP WITH TIME ZONE, 
	closed_at TIMESTAMP WITH TIME ZONE, 
	last_activity_at TIMESTAMP WITH TIME ZONE DEFAULT 'now()' NOT NULL, 
	reopen_count INTEGER NOT NULL, 
	parent_case_id INTEGER, 
	duplicate_group_id VARCHAR(64), 
	dedupe_state VARCHAR(16) NOT NULL, 
	dedupe_score FLOAT, 
	client_ref VARCHAR(80), 
	captured_offline_at TIMESTAMP WITH TIME ZONE, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_case_campus_number UNIQUE (campus_id, case_number), 
	CONSTRAINT ck_status CHECK (status IN ('DRAFT', 'SUBMITTED', 'VALIDATING', 'ROUTED', 'ASSIGNED', 'IN_PROGRESS', 'WAITING_FOR_USER', 'WAITING_FOR_APPROVAL', 'ESCALATED', 'RESOLVED', 'VERIFICATION_REQUIRED', 'CLOSED', 'REOPENED', 'CANCELLED')), 
	CONSTRAINT ck_cases_priority CHECK (priority IN ('LOW', 'NORMAL', 'HIGH', 'CRITICAL', 'URGENT')), 
	CONSTRAINT ck_cases_source_channel CHECK (source_channel IN ('PWA', 'WEB_DESKTOP', 'KIOSK', 'ASSISTED_DESK', 'QR', 'PHONE', 'EMAIL', 'WALK_IN', 'AGENT', 'SYSTEM')), 
	CONSTRAINT ck_cases_sla_state CHECK (sla_state IN ('NO_SLA', 'ON_TIME', 'AT_RISK', 'BREACHED', 'MET', 'MISSED')), 
	CONSTRAINT ck_cases_verification_state CHECK (verification_state IN ('NOT_REQUIRED', 'PENDING', 'VERIFIED', 'DISPUTED')), 
	CONSTRAINT ck_cases_dedupe_state CHECK (dedupe_state IN ('NONE', 'SUSPECTED', 'CONFIRMED')), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(requester_id) REFERENCES users (id) ON DELETE SET NULL, 
	FOREIGN KEY(requester_student_id) REFERENCES students (id) ON DELETE SET NULL, 
	FOREIGN KEY(created_by_id) REFERENCES users (id) ON DELETE SET NULL, 
	FOREIGN KEY(service_id) REFERENCES services (id) ON DELETE SET NULL, 
	FOREIGN KEY(location_id) REFERENCES locations (id) ON DELETE SET NULL, 
	FOREIGN KEY(asset_id) REFERENCES assets (id) ON DELETE SET NULL, 
	FOREIGN KEY(department_id) REFERENCES departments (id) ON DELETE SET NULL, 
	FOREIGN KEY(assigned_staff_id) REFERENCES staff (id) ON DELETE SET NULL, 
	FOREIGN KEY(parent_case_id) REFERENCES cases (id) ON DELETE SET NULL
);

CREATE INDEX ix_cases_asset ON cases (asset_id, created_at);

CREATE INDEX ix_cases_assignee ON cases (assigned_staff_id, status);

CREATE INDEX ix_cases_campus_id ON cases (campus_id);

CREATE INDEX ix_cases_client_ref ON cases (client_ref);

CREATE INDEX ix_cases_dept_queue ON cases (campus_id, department_id, status);

CREATE INDEX ix_cases_due ON cases (campus_id, due_at);

CREATE INDEX ix_cases_duplicate_group_id ON cases (duplicate_group_id);

CREATE INDEX ix_cases_location ON cases (location_id, created_at);

CREATE INDEX ix_cases_queue ON cases (campus_id, status, priority);

CREATE INDEX ix_cases_requester ON cases (requester_id, created_at);

CREATE INDEX ix_cases_service ON cases (campus_id, service_key, created_at);

CREATE INDEX ix_cases_service_key ON cases (service_key);

CREATE TABLE audit_logs (
	campus_id INTEGER, 
	event_type VARCHAR(40) NOT NULL, 
	actor_id INTEGER, 
	actor_role VARCHAR(32), 
	actor_kind VARCHAR(16) NOT NULL, 
	case_id INTEGER, 
	entity_type VARCHAR(40) NOT NULL, 
	entity_id VARCHAR(64), 
	source_channel VARCHAR(24) NOT NULL, 
	device_id VARCHAR(80), 
	idempotency_key VARCHAR(80), 
	payload JSONB NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT 'now()' NOT NULL, 
	id SERIAL NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_audit_logs_actor_kind CHECK (actor_kind IN ('USER', 'AGENT', 'SYSTEM', 'INTEGRATION')), 
	CONSTRAINT uq_audit_logs_idempotency UNIQUE (idempotency_key), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(actor_id) REFERENCES users (id) ON DELETE SET NULL, 
	FOREIGN KEY(case_id) REFERENCES cases (id) ON DELETE SET NULL
);

CREATE INDEX ix_audit_logs_campus_time ON audit_logs (campus_id, created_at);

CREATE INDEX ix_audit_logs_case ON audit_logs (case_id, created_at);

CREATE INDEX ix_audit_logs_entity ON audit_logs (entity_type, entity_id);

CREATE INDEX ix_audit_logs_type ON audit_logs (event_type, created_at);

CREATE TABLE case_approvals (
	campus_id INTEGER NOT NULL, 
	case_id INTEGER NOT NULL, 
	step_key VARCHAR(48) NOT NULL, 
	sequence INTEGER NOT NULL, 
	approver_role VARCHAR(32) NOT NULL, 
	approver_id INTEGER, 
	state VARCHAR(16) NOT NULL, 
	requested_at TIMESTAMP WITH TIME ZONE DEFAULT 'now()' NOT NULL, 
	decided_at TIMESTAMP WITH TIME ZONE, 
	decision_note TEXT, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_state CHECK (state IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'EXPIRED')), 
	CONSTRAINT ck_case_approvals_role CHECK (approver_role IN ('SUPER_ADMIN', 'ADMIN', 'WARDEN', 'DEPARTMENT_HEAD', 'STAFF', 'SECURITY', 'HELPDESK_OPERATOR', 'STUDENT')), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(case_id) REFERENCES cases (id) ON DELETE CASCADE, 
	FOREIGN KEY(approver_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_case_approvals_campus_id ON case_approvals (campus_id);

CREATE INDEX ix_case_approvals_pending ON case_approvals (campus_id, state, created_at);

CREATE TABLE case_assignments (
	campus_id INTEGER NOT NULL, 
	case_id INTEGER NOT NULL, 
	staff_id INTEGER, 
	assigned_by_id INTEGER, 
	assignment_type VARCHAR(24) NOT NULL, 
	reason VARCHAR(240), 
	is_active BOOLEAN NOT NULL, 
	unassigned_at TIMESTAMP WITH TIME ZONE, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(case_id) REFERENCES cases (id) ON DELETE CASCADE, 
	FOREIGN KEY(staff_id) REFERENCES staff (id) ON DELETE SET NULL, 
	FOREIGN KEY(assigned_by_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_case_assignments_campus_id ON case_assignments (campus_id);

CREATE INDEX ix_case_assignments_case ON case_assignments (case_id, is_active);

CREATE TABLE case_attachments (
	campus_id INTEGER NOT NULL, 
	case_id INTEGER NOT NULL, 
	uploaded_by_id INTEGER, 
	kind VARCHAR(24) NOT NULL, 
	filename VARCHAR(240) NOT NULL, 
	content_type VARCHAR(120) NOT NULL, 
	size_bytes INTEGER NOT NULL, 
	storage_path VARCHAR(400) NOT NULL, 
	sha256 VARCHAR(64), 
	note VARCHAR(240), 
	client_ref VARCHAR(80), 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(case_id) REFERENCES cases (id) ON DELETE CASCADE, 
	FOREIGN KEY(uploaded_by_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_case_attachments_campus_id ON case_attachments (campus_id);

CREATE INDEX ix_case_attachments_case ON case_attachments (case_id, created_at);

CREATE TABLE case_comments (
	campus_id INTEGER NOT NULL, 
	case_id INTEGER NOT NULL, 
	author_id INTEGER, 
	author_role VARCHAR(32), 
	body TEXT NOT NULL, 
	visibility VARCHAR(16) NOT NULL, 
	source_channel VARCHAR(24) NOT NULL, 
	client_ref VARCHAR(80), 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_case_comment_client_ref UNIQUE (case_id, client_ref), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(case_id) REFERENCES cases (id) ON DELETE CASCADE, 
	FOREIGN KEY(author_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_case_comments_campus_id ON case_comments (campus_id);

CREATE INDEX ix_case_comments_case ON case_comments (case_id, created_at);

CREATE TABLE case_events (
	campus_id INTEGER NOT NULL, 
	case_id INTEGER NOT NULL, 
	event_type VARCHAR(40) NOT NULL, 
	actor_id INTEGER, 
	actor_role VARCHAR(32), 
	actor_kind VARCHAR(16) NOT NULL, 
	from_status VARCHAR(32), 
	to_status VARCHAR(32), 
	step_key VARCHAR(48), 
	source_channel VARCHAR(24) NOT NULL, 
	device_id VARCHAR(80), 
	idempotency_key VARCHAR(80), 
	payload JSONB NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT 'now()' NOT NULL, 
	id SERIAL NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_case_event_idempotency UNIQUE (idempotency_key, case_id), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(case_id) REFERENCES cases (id) ON DELETE CASCADE, 
	FOREIGN KEY(actor_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_case_events_campus_id ON case_events (campus_id);

CREATE INDEX ix_case_events_case ON case_events (case_id, created_at);

CREATE TABLE documents (
	campus_id INTEGER NOT NULL, 
	case_id INTEGER, 
	student_id INTEGER, 
	kind VARCHAR(32) NOT NULL, 
	serial_no VARCHAR(32) NOT NULL, 
	verification_code VARCHAR(24) NOT NULL, 
	title VARCHAR(200) NOT NULL, 
	storage_path VARCHAR(400) NOT NULL, 
	sha256 VARCHAR(64), 
	issued_at TIMESTAMP WITH TIME ZONE DEFAULT 'now()' NOT NULL, 
	generated_by_id INTEGER, 
	is_revoked BOOLEAN NOT NULL, 
	revoke_reason VARCHAR(240), 
	meta JSONB NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_documents_serial UNIQUE (serial_no), 
	CONSTRAINT uq_documents_verification_code UNIQUE (verification_code), 
	CONSTRAINT ck_documents_kind CHECK (kind IN ('BONAFIDE_CERTIFICATE', 'FEE_RECEIPT', 'GATE_PASS', 'OTHER')), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(case_id) REFERENCES cases (id) ON DELETE SET NULL, 
	FOREIGN KEY(student_id) REFERENCES students (id) ON DELETE SET NULL, 
	FOREIGN KEY(generated_by_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_documents_campus_id ON documents (campus_id);

CREATE INDEX ix_documents_case ON documents (case_id, created_at);

CREATE TABLE gate_passes (
	campus_id INTEGER NOT NULL, 
	case_id INTEGER NOT NULL, 
	student_id INTEGER NOT NULL, 
	pass_code VARCHAR(32) NOT NULL, 
	state VARCHAR(20) NOT NULL, 
	valid_from TIMESTAMP WITH TIME ZONE NOT NULL, 
	valid_to TIMESTAMP WITH TIME ZONE NOT NULL, 
	destination VARCHAR(160), 
	reason TEXT, 
	issued_at TIMESTAMP WITH TIME ZONE DEFAULT 'now()' NOT NULL, 
	issued_by_id INTEGER, 
	revoked_at TIMESTAMP WITH TIME ZONE, 
	revoke_reason VARCHAR(240), 
	qr_payload VARCHAR(160), 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT uq_gate_pass_code UNIQUE (pass_code), 
	CONSTRAINT ck_state CHECK (state IN ('ISSUED', 'PARTIALLY_USED', 'USED', 'EXPIRED', 'REVOKED')), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(case_id) REFERENCES cases (id) ON DELETE CASCADE, 
	FOREIGN KEY(student_id) REFERENCES students (id) ON DELETE CASCADE, 
	FOREIGN KEY(issued_by_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_gate_passes_campus_id ON gate_passes (campus_id);

CREATE INDEX ix_gate_passes_campus_state ON gate_passes (campus_id, state, valid_to);

CREATE TABLE notice_actions (
	campus_id INTEGER NOT NULL, 
	notice_id INTEGER NOT NULL, 
	user_id INTEGER NOT NULL, 
	action_type VARCHAR(24) NOT NULL, 
	case_id INTEGER, 
	payload JSONB NOT NULL, 
	completed_at TIMESTAMP WITH TIME ZONE DEFAULT 'now()' NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_notice_actions_type CHECK (action_type IN ('READ', 'ACKNOWLEDGE', 'SUBMIT_FORM', 'VIEW_DOCUMENT', 'REGISTER', 'OPEN_CASE', 'VIEW_TIMETABLE')), 
	CONSTRAINT uq_notice_action_unique UNIQUE (notice_id, user_id, action_type), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(notice_id) REFERENCES notices (id) ON DELETE CASCADE, 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	FOREIGN KEY(case_id) REFERENCES cases (id) ON DELETE SET NULL
);

CREATE INDEX ix_notice_actions_campus_id ON notice_actions (campus_id);

CREATE TABLE notifications (
	campus_id INTEGER NOT NULL, 
	user_id INTEGER NOT NULL, 
	category VARCHAR(32) NOT NULL, 
	title VARCHAR(200) NOT NULL, 
	body VARCHAR(600) NOT NULL, 
	priority VARCHAR(16) NOT NULL, 
	state VARCHAR(16) NOT NULL, 
	action_label VARCHAR(80), 
	action_type VARCHAR(40), 
	action_target VARCHAR(120), 
	case_id INTEGER, 
	notice_id INTEGER, 
	dedupe_key VARCHAR(120), 
	delivered_at TIMESTAMP WITH TIME ZONE, 
	read_at TIMESTAMP WITH TIME ZONE, 
	actioned_at TIMESTAMP WITH TIME ZONE, 
	expires_at TIMESTAMP WITH TIME ZONE, 
	payload JSONB NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_notifications_category CHECK (category IN ('CASE_UPDATE', 'APPROVAL', 'CERTIFICATE_READY', 'LEAVE_STATUS', 'GATE_PASS', 'TIMETABLE', 'NOTICE', 'URGENT_ANNOUNCEMENT', 'SLA_ALERT', 'SYSTEM', 'MESS', 'ACADEMIC', 'HOSTEL')), 
	CONSTRAINT ck_notifications_state CHECK (state IN ('SENT', 'DELIVERED', 'READ', 'ACTIONED', 'FAILED')), 
	CONSTRAINT ck_notifications_priority CHECK (priority IN ('LOW', 'NORMAL', 'HIGH', 'CRITICAL', 'URGENT')), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	FOREIGN KEY(case_id) REFERENCES cases (id) ON DELETE SET NULL, 
	FOREIGN KEY(notice_id) REFERENCES notices (id) ON DELETE SET NULL
);

CREATE INDEX ix_notifications_campus_id ON notifications (campus_id);

CREATE INDEX ix_notifications_dedupe_key ON notifications (dedupe_key);

CREATE INDEX ix_notifications_user_category ON notifications (user_id, category, created_at);

CREATE INDEX ix_notifications_user_state ON notifications (user_id, state, created_at);

CREATE TABLE gate_logs (
	campus_id INTEGER NOT NULL, 
	gate_pass_id INTEGER, 
	student_id INTEGER, 
	case_id INTEGER, 
	direction VARCHAR(8) NOT NULL, 
	occurred_at TIMESTAMP WITH TIME ZONE DEFAULT 'now()' NOT NULL, 
	gate_location_id INTEGER, 
	logged_by_id INTEGER, 
	device_id VARCHAR(80), 
	source_channel VARCHAR(24) NOT NULL, 
	offline_captured_at TIMESTAMP WITH TIME ZONE, 
	client_ref VARCHAR(80), 
	note VARCHAR(240), 
	payload JSONB NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_gate_logs_direction CHECK (direction IN ('ENTRY', 'EXIT')), 
	CONSTRAINT uq_gate_logs_client_ref UNIQUE (client_ref), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(gate_pass_id) REFERENCES gate_passes (id) ON DELETE SET NULL, 
	FOREIGN KEY(student_id) REFERENCES students (id) ON DELETE SET NULL, 
	FOREIGN KEY(case_id) REFERENCES cases (id) ON DELETE SET NULL, 
	FOREIGN KEY(gate_location_id) REFERENCES locations (id) ON DELETE SET NULL, 
	FOREIGN KEY(logged_by_id) REFERENCES users (id) ON DELETE SET NULL
);

CREATE INDEX ix_gate_logs_campus_id ON gate_logs (campus_id);

CREATE INDEX ix_gate_logs_campus_time ON gate_logs (campus_id, occurred_at);

CREATE INDEX ix_gate_logs_student ON gate_logs (student_id, occurred_at);

CREATE TABLE notification_deliveries (
	campus_id INTEGER NOT NULL, 
	notification_id INTEGER NOT NULL, 
	channel VARCHAR(16) NOT NULL, 
	state VARCHAR(16) NOT NULL, 
	target VARCHAR(120), 
	attempts INTEGER NOT NULL, 
	max_attempts INTEGER NOT NULL, 
	next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	last_error VARCHAR(400), 
	provider VARCHAR(32), 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_notification_deliveries_channel CHECK (channel IN ('IN_APP', 'PUSH', 'TELEGRAM', 'WHATSAPP')), 
	CONSTRAINT ck_notification_deliveries_state CHECK (state IN ('QUEUED', 'DELIVERED', 'FAILED', 'CANCELLED')), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(notification_id) REFERENCES notifications (id) ON DELETE CASCADE
);

CREATE INDEX ix_notification_deliveries_campus_id ON notification_deliveries (campus_id);

CREATE INDEX ix_notification_deliveries_due ON notification_deliveries (state, next_attempt_at);

CREATE INDEX ix_notification_deliveries_notification_id ON notification_deliveries (notification_id);

CREATE TABLE notification_events (
	campus_id INTEGER NOT NULL, 
	notification_id INTEGER NOT NULL, 
	channel VARCHAR(16) NOT NULL, 
	state VARCHAR(16) NOT NULL, 
	provider VARCHAR(32) NOT NULL, 
	detail VARCHAR(400), 
	payload JSONB NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT 'now()' NOT NULL, 
	id SERIAL NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_notification_events_channel CHECK (channel IN ('IN_APP', 'PUSH', 'TELEGRAM', 'WHATSAPP')), 
	CONSTRAINT ck_notification_events_state CHECK (state IN ('SENT', 'DELIVERED', 'READ', 'ACTIONED', 'FAILED')), 
	FOREIGN KEY(campus_id) REFERENCES campuses (id) ON DELETE CASCADE, 
	FOREIGN KEY(notification_id) REFERENCES notifications (id) ON DELETE CASCADE
);

CREATE INDEX ix_notification_events_campus_id ON notification_events (campus_id);

CREATE INDEX ix_notification_events_notification ON notification_events (notification_id, created_at);

-- ============================================================================
-- 3. Append-only guards
-- ============================================================================
-- The audit trail is the product's evidence layer. The ORM already refuses to
-- update these rows; these triggers make the guarantee a property of the
-- database itself, so an ad-hoc SQL session cannot rewrite history either.
-- The same function is created by Alembic migration 0002.
create or replace function campus_relay_block_mutation() returns trigger as $$
begin
    raise exception
        'Campus Relay append-only guard: % on %.% is not permitted',
        tg_op, tg_table_schema, tg_table_name
        using errcode = 'restrict_violation',
              hint = 'Audit and event records are immutable. Insert a new record instead.';
end;
$$ language plpgsql;

do $$
declare
    t text;
begin
    foreach t in array array['case_events', 'audit_logs', 'notification_events', 'gate_logs']
    loop
        execute format('drop trigger if exists trg_%1$s_append_only on %1$s', t);
        execute format(
            'create trigger trg_%1$s_append_only before update or delete on %1$s
             for each row execute function campus_relay_block_mutation()', t);
    end loop;
end;
$$;

-- ============================================================================
-- 4. Row-level security (defence in depth)
-- ============================================================================
-- RLS is enabled on every table with NO permissive policies. The API connects
-- with a privileged role that bypasses RLS; the anon and authenticated roles
-- (used by Supabase client libraries) therefore read nothing, even if a key
-- leaks. If you ever expose a table directly through PostgREST, add an explicit
-- policy for it here rather than disabling RLS.
do $$
declare
    t text;
begin
    for t in
        select tablename from pg_tables where schemaname = 'public'
    loop
        execute format('alter table public.%I enable row level security', t);
    end loop;
end;
$$;

-- The API role bypasses RLS; grant it the schema usage it needs.
grant usage on schema public to anon, authenticated;

-- ============================================================================
-- 5. Storage (attachments)
-- ============================================================================
-- Notice circulars (images/PDFs) and case evidence are uploaded through the API,
-- which writes them to the media root and serves them from
-- /api/v1/notices/{id}/attachment and /api/v1/cases/{id}/attachments/{aid}.
--
-- Two supported storage modes:
--   * On-disk (default): set MEDIA_ROOT to a persistent volume. Nothing else
--     to do here.
--   * Supabase Storage: create the bucket below and mount it, or point
--     MEDIA_ROOT at a synced directory. Attachments are fetched by URL by the
--     external messaging channels, so PUBLIC_BASE_URL must be reachable.
insert into storage.buckets (id, name, public)
values ('campus-relay-media', 'campus-relay-media', false)
on conflict (id) do nothing;

-- ============================================================================
-- 6. Verification
-- ============================================================================
-- Expect 42 tables. A quick sanity check after running this file:
--   select count(*) from information_schema.tables
--    where table_schema = 'public' and table_type = 'BASE TABLE';
select count(*) as campus_relay_tables
from information_schema.tables
where table_schema = 'public' and table_type = 'BASE TABLE';
