"""Generate supabase/schema.sql from the ORM metadata.

The SQLAlchemy models are the single source of truth for the database shape;
Alembic migrations are how the running API evolves. Supabase, however, is often
set up by pasting SQL into its dashboard, so this script renders the *current*
schema - tables, constraints, indexes - plus the Supabase-specific pieces that
Alembic deliberately does not own: row-level security, the storage bucket for
media, and the append-only triggers.

Run from the backend directory:

    python -m scripts.export_supabase_schema

It writes supabase/schema.sql at the repository root. Re-run it after changing a
model; do not hand-edit the generated section.
"""

from __future__ import annotations

from pathlib import Path

from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateIndex, CreateTable

import app.models  # noqa: F401  - importing registers every table on Base.metadata
from app.models import Base

REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT = REPO_ROOT / "supabase" / "schema.sql"

HEADER = """-- ============================================================================
-- CAMPUS RELAY - SUPABASE SCHEMA
-- ============================================================================
--
-- WHAT THIS IS
--   The complete database schema for a Campus Relay deployment on Supabase:
--   every table, constraint, index, the append-only triggers, row-level
--   security, and the storage bucket that backs attachments.
--
-- SOURCE OF TRUTH
--   SQLAlchemy models (backend/app/models) own the shape; Alembic owns the
--   migration history. The table DDL below is GENERATED by
--   `python -m scripts.export_supabase_schema`. Treat the generated section as
--   read-only: change a model, re-run the generator, and commit the result.
--
-- HOW TO USE IT
--   Option A - Supabase dashboard: Database -> SQL Editor -> New query, paste
--              this whole file, Run.
--   Option B - psql:  psql "$DATABASE_URL" -f supabase/schema.sql
--   Option C - let Alembic do it:  cd backend && alembic upgrade head
--              (equivalent for the table DDL; it will not create the storage
--              bucket or the RLS statements, so run this file too if you want
--              those)
--
-- CONNECTION NOTE
--   The API connects as a privileged Postgres role (see DATABASE_URL). RLS is
--   enabled defensively so that a leaked anon/service key cannot read campus
--   data through PostgREST - there are deliberately NO permissive policies.
--   All access is mediated by the API, never by the browser.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- 1. Extensions
-- ---------------------------------------------------------------------------
-- Only pgcrypto is needed beyond the Postgres defaults: `gen_random_uuid()` is
-- used by Supabase tooling, and JSONB is built in.
create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- 2. Schema
-- ---------------------------------------------------------------------------
-- Everything lives in `public`, which is what PostgREST exposes and what the
-- API's search_path resolves to.

"""

FOOTER = """

-- ============================================================================
-- 3. Append-only guards
-- ============================================================================
-- The audit trail is the product's evidence layer. The ORM already refuses to
-- update these rows; these triggers make the guarantee a property of the
-- database itself, so an ad-hoc SQL session cannot rewrite history either.
-- The same function is created by Alembic migration 0002.
create or replace function campus_relay_block_mutation() returns trigger as $$
begin
    raise exception
        'Campus Relay append-only guard: % on %.% is not permitted',
        tg_op, tg_table_schema, tg_table_name
        using errcode = 'restrict_violation',
              hint = 'Audit and event records are immutable. Insert a new record instead.';
end;
$$ language plpgsql;

do $$
declare
    t text;
begin
    foreach t in array array['case_events', 'audit_logs', 'notification_events', 'gate_logs']
    loop
        execute format('drop trigger if exists trg_%1$s_append_only on %1$s', t);
        execute format(
            'create trigger trg_%1$s_append_only before update or delete on %1$s
             for each row execute function campus_relay_block_mutation()', t);
    end loop;
end;
$$;

-- ============================================================================
-- 4. Row-level security (defence in depth)
-- ============================================================================
-- RLS is enabled on every table with NO permissive policies. The API connects
-- with a privileged role that bypasses RLS; the anon and authenticated roles
-- (used by Supabase client libraries) therefore read nothing, even if a key
-- leaks. If you ever expose a table directly through PostgREST, add an explicit
-- policy for it here rather than disabling RLS.
do $$
declare
    t text;
begin
    for t in
        select tablename from pg_tables where schemaname = 'public'
    loop
        execute format('alter table public.%I enable row level security', t);
    end loop;
end;
$$;

-- The API role bypasses RLS; grant it the schema usage it needs.
grant usage on schema public to anon, authenticated;

-- ============================================================================
-- 5. Storage (attachments)
-- ============================================================================
-- Notice circulars (images/PDFs) and case evidence are uploaded through the API,
-- which writes them to the media root and serves them from
-- /api/v1/notices/{id}/attachment and /api/v1/cases/{id}/attachments/{aid}.
--
-- Two supported storage modes:
--   * On-disk (default): set MEDIA_ROOT to a persistent volume. Nothing else
--     to do here.
--   * Supabase Storage: create the bucket below and mount it, or point
--     MEDIA_ROOT at a synced directory. Attachments are fetched by URL by the
--     external messaging channels, so PUBLIC_BASE_URL must be reachable.
insert into storage.buckets (id, name, public)
values ('campus-relay-media', 'campus-relay-media', false)
on conflict (id) do nothing;

-- ============================================================================
-- 6. Verification
-- ============================================================================
-- Expect 42 tables. A quick sanity check after running this file:
--   select count(*) from information_schema.tables
--    where table_schema = 'public' and table_type = 'BASE TABLE';
select count(*) as campus_relay_tables
from information_schema.tables
where table_schema = 'public' and table_type = 'BASE TABLE';
"""


def render_ddl() -> str:
    dialect = postgresql.dialect()
    parts: list[str] = []
    for table in Base.metadata.sorted_tables:
        parts.append(str(CreateTable(table).compile(dialect=dialect)).strip() + ";")
        for index in sorted(table.indexes, key=lambda i: i.name or ""):
            parts.append(str(CreateIndex(index).compile(dialect=dialect)).strip() + ";")
    return "\n\n".join(parts)


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(HEADER + render_ddl() + FOOTER, encoding="utf-8")
    print(f"wrote {OUTPUT} ({len(Base.metadata.sorted_tables)} tables)")


if __name__ == "__main__":
    main()
