"""initial campus relay schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-09-20 02:53:44.243387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campuses',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=80), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('default_language', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('permissions',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('roles',
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("key IN ('SUPER_ADMIN', 'ADMIN', 'WARDEN', 'DEPARTMENT_HEAD', 'STAFF', 'SECURITY', 'HELPDESK_OPERATOR', 'STUDENT')", name='ck_roles_key'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('batches',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campus_id', 'name', name='uq_batch_campus_name')
    )
    op.create_index(op.f('ix_batches_campus_id'), 'batches', ['campus_id'], unique=False)
    op.create_table('departments',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('head_user_id', sa.Integer(), nullable=True),
    sa.Column('sla_multiplier', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['head_user_id'], ['users.id'], name='fk_department_head_user', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campus_id', 'code', name='uq_department_campus_code')
    )
    op.create_index(op.f('ix_departments_campus_id'), 'departments', ['campus_id'], unique=False)
    op.create_table('policies',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('service_key', sa.String(length=48), nullable=True),
    sa.Column('effect', sa.String(length=16), nullable=False),
    sa.Column('evaluation_order', sa.Integer(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("effect IN ('ALLOW', 'DENY', 'REQUIRE')", name='ck_effect'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campus_id', 'key', name='uq_policy_campus_key')
    )
    op.create_index(op.f('ix_policies_campus_id'), 'policies', ['campus_id'], unique=False)
    op.create_index('ix_policies_campus_service', 'policies', ['campus_id', 'service_key'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('sla_rules',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('service_key', sa.String(length=48), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('target_minutes', sa.Integer(), nullable=False),
    sa.Column('at_risk_ratio', sa.Float(), nullable=False),
    sa.Column('escalate_to_role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("escalate_to_role IN ('SUPER_ADMIN', 'ADMIN', 'WARDEN', 'DEPARTMENT_HEAD', 'STAFF', 'SECURITY', 'HELPDESK_OPERATOR', 'STUDENT')", name='ck_sla_rules_escalate_role'),
    sa.CheckConstraint("priority IN ('LOW', 'NORMAL', 'HIGH', 'CRITICAL', 'URGENT')", name='ck_sla_rules_priority'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campus_id', 'service_key', 'priority', name='uq_sla_rule_scope')
    )
    op.create_index(op.f('ix_sla_rules_campus_id'), 'sla_rules', ['campus_id'], unique=False)
    op.create_table('users',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=180), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=24), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campus_id', 'email', name='uq_user_campus_email')
    )
    op.create_index(op.f('ix_users_campus_id'), 'users', ['campus_id'], unique=False)
    op.create_index('ix_users_campus_role', 'users', ['campus_id', 'role_id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('workflows',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('initial_state', sa.String(length=32), nullable=False),
    sa.Column('allowed_states', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campus_id', 'key', name='uq_workflow_campus_key')
    )
    op.create_index(op.f('ix_workflows_campus_id'), 'workflows', ['campus_id'], unique=False)
    op.create_table('years',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campus_id', 'name', name='uq_year_campus_name')
    )
    op.create_index(op.f('ix_years_campus_id'), 'years', ['campus_id'], unique=False)
    op.create_table('branches',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campus_id', 'code', name='uq_branch_campus_code')
    )
    op.create_index(op.f('ix_branches_campus_id'), 'branches', ['campus_id'], unique=False)
    op.create_index(op.f('ix_branches_department_id'), 'branches', ['department_id'], unique=False)
    op.create_table('devices',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_uid', sa.String(length=80), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('push_subscription', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_uid', name='uq_device_user_uid')
    )
    op.create_index(op.f('ix_devices_campus_id'), 'devices', ['campus_id'], unique=False)
    op.create_table('hostels',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('gender', sa.String(length=12), nullable=False),
    sa.Column('warden_user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warden_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campus_id', 'code', name='uq_hostel_campus_code')
    )
    op.create_index(op.f('ix_hostels_campus_id'), 'hostels', ['campus_id'], unique=False)
    op.create_table('notices',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.String(length=300), nullable=True),
    sa.Column('notice_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('publish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('acknowledgement_required', sa.Boolean(), nullable=False),
    sa.Column('required_action', sa.String(length=24), nullable=True),
    sa.Column('required_action_label', sa.String(length=80), nullable=True),
    sa.Column('attachment_path', sa.String(length=400), nullable=True),
    sa.Column('attachment_name', sa.String(length=240), nullable=True),
    sa.Column('image_path', sa.String(length=400), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('share_enabled', sa.Boolean(), nullable=False),
    sa.Column('audience_summary', sa.String(length=240), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("notice_type IN ('NORMAL', 'IMPORTANT', 'URGENT', 'EMERGENCY')", name='ck_notices_type'),
    sa.CheckConstraint("priority IN ('LOW', 'NORMAL', 'HIGH', 'CRITICAL', 'URGENT')", name='ck_notices_priority'),
    sa.CheckConstraint("required_action IN ('READ', 'ACKNOWLEDGE', 'SUBMIT_FORM', 'VIEW_DOCUMENT', 'REGISTER', 'OPEN_CASE', 'VIEW_TIMETABLE')", name='ck_notices_required_action'),
    sa.CheckConstraint("status IN ('DRAFT', 'SCHEDULED', 'PUBLISHED', 'EXPIRED', 'ARCHIVED')", name='ck_notices_status'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token', name='uq_notices_share_token')
    )
    op.create_index(op.f('ix_notices_campus_id'), 'notices', ['campus_id'], unique=False)
    op.create_index('ix_notices_campus_status', 'notices', ['campus_id', 'status', 'publish_at'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('in_app', sa.Boolean(), nullable=False),
    sa.Column('push', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('CASE_UPDATE', 'APPROVAL', 'CERTIFICATE_READY', 'LEAVE_STATUS', 'GATE_PASS', 'TIMETABLE', 'NOTICE', 'URGENT_ANNOUNCEMENT', 'SLA_ALERT', 'SYSTEM', 'MESS', 'ACADEMIC', 'HOSTEL')", name='ck_notification_prefs_category'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', name='uq_notification_pref_user_category')
    )
    op.create_index(op.f('ix_notification_preferences_campus_id'), 'notification_preferences', ['campus_id'], unique=False)
    op.create_table('services',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('icon', sa.String(length=32), nullable=False),
    sa.Column('default_priority', sa.String(length=16), nullable=False),
    sa.Column('default_sla_minutes', sa.Integer(), nullable=False),
    sa.Column('allowed_requester_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('form_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requires_attachment', sa.Boolean(), nullable=False),
    sa.Column('allow_anonymous_location', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('HOSTEL', 'FACILITY', 'ACADEMIC', 'ADMINISTRATIVE', 'FINANCE', 'MESS', 'SECURITY', 'OTHER')", name='ck_category'),
    sa.CheckConstraint("default_priority IN ('LOW', 'NORMAL', 'HIGH', 'CRITICAL', 'URGENT')", name='ck_services_priority'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campus_id', 'key', name='uq_service_campus_key')
    )
    op.create_index(op.f('ix_services_campus_id'), 'services', ['campus_id'], unique=False)
    op.create_table('staff',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('designation', sa.String(length=80), nullable=False),
    sa.Column('employee_code', sa.String(length=32), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('workload_capacity', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_staff_user')
    )
    op.create_index(op.f('ix_staff_campus_id'), 'staff', ['campus_id'], unique=False)
    op.create_index(op.f('ix_staff_department_id'), 'staff', ['department_id'], unique=False)
    op.create_table('sync_operations',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=80), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('operation', sa.String(length=24), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('source_channel', sa.String(length=24), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('client_base', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('captured_offline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("operation IN ('CASE_CREATE', 'CASE_COMMENT', 'CASE_STATUS', 'CASE_VERIFY', 'NOTICE_READ', 'NOTICE_ACTION', 'NOTIFICATION_READ', 'GATE_LOG')", name='ck_sync_operations_operation'),
    sa.CheckConstraint("status IN ('QUEUED', 'SYNCING', 'SYNCED', 'FAILED_RETRYING', 'CONFLICT', 'FAILED_REQUIRES_ACTION')", name='ck_sync_operations_status'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_sync_operations_idempotency')
    )
    op.create_index(op.f('ix_sync_operations_campus_id'), 'sync_operations', ['campus_id'], unique=False)
    op.create_index('ix_sync_operations_status', 'sync_operations', ['status', 'updated_at'], unique=False)
    op.create_index('ix_sync_operations_user_device', 'sync_operations', ['user_id', 'device_id', 'created_at'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('step_type', sa.String(length=24), nullable=False),
    sa.Column('responsible_role', sa.String(length=32), nullable=True),
    sa.Column('sla_minutes', sa.Integer(), nullable=True),
    sa.Column('requires_note', sa.Boolean(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('transitions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("responsible_role IN ('SUPER_ADMIN', 'ADMIN', 'WARDEN', 'DEPARTMENT_HEAD', 'STAFF', 'SECURITY', 'HELPDESK_OPERATOR', 'STUDENT')", name='ck_workflow_steps_role'),
    sa.CheckConstraint("step_type IN ('APPROVAL', 'ASSIGNMENT', 'ACTION', 'RESOLUTION', 'VERIFICATION', 'NOTIFICATION')", name='ck_step_type'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'key', name='uq_workflow_step_key')
    )
    op.create_index(op.f('ix_workflow_steps_workflow_id'), 'workflow_steps', ['workflow_id'], unique=False)
    op.create_table('blocks',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('hostel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostel_id', 'code', name='uq_block_hostel_code')
    )
    op.create_index(op.f('ix_blocks_campus_id'), 'blocks', ['campus_id'], unique=False)
    op.create_index(op.f('ix_blocks_hostel_id'), 'blocks', ['hostel_id'], unique=False)
    op.create_table('notice_reads',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_channel', sa.String(length=24), nullable=False),
    sa.Column('device_id', sa.String(length=80), nullable=True),
    sa.Column('offline_captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notice_id', 'user_id', name='uq_notice_read_user')
    )
    op.create_index(op.f('ix_notice_reads_campus_id'), 'notice_reads', ['campus_id'], unique=False)
    op.create_index('ix_notice_reads_notice_state', 'notice_reads', ['notice_id', 'state'], unique=False)
    op.create_index('ix_notice_reads_user', 'notice_reads', ['user_id', 'created_at'], unique=False)
    op.create_table('notice_shares',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('shared_by_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=24), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('last_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token', name='uq_notice_share_token')
    )
    op.create_index(op.f('ix_notice_shares_campus_id'), 'notice_shares', ['campus_id'], unique=False)
    op.create_table('notice_targets',
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_value', sa.String(length=64), nullable=True),
    sa.Column('include', sa.Boolean(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("target_type IN ('CAMPUS', 'DEPARTMENT', 'BRANCH', 'YEAR', 'BATCH', 'HOSTEL', 'BLOCK', 'ROLE', 'USER')", name='ck_notice_targets_type'),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notice_id', 'target_type', 'target_id', name='uq_notice_target_unique')
    )
    op.create_index('ix_notice_targets_lookup', 'notice_targets', ['target_type', 'target_id'], unique=False)
    op.create_index('ix_notice_targets_notice', 'notice_targets', ['notice_id'], unique=False)
    op.create_table('rooms',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('hostel_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=16), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('occupant_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id', 'number', name='uq_room_block_number')
    )
    op.create_index(op.f('ix_rooms_block_id'), 'rooms', ['block_id'], unique=False)
    op.create_index(op.f('ix_rooms_campus_id'), 'rooms', ['campus_id'], unique=False)
    op.create_index(op.f('ix_rooms_hostel_id'), 'rooms', ['hostel_id'], unique=False)
    op.create_table('locations',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('building', sa.String(length=80), nullable=True),
    sa.Column('hostel_id', sa.Integer(), nullable=True),
    sa.Column('block_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('qr_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('HOSTEL_ROOM', 'WASHROOM', 'WATER_COOLER', 'CORRIDOR', 'CLASSROOM', 'LAB', 'LIBRARY', 'MESS', 'GATE', 'OFFICE', 'EQUIPMENT', 'OTHER')", name='ck_kind'),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campus_id', 'code', name='uq_location_campus_code')
    )
    op.create_index(op.f('ix_locations_campus_id'), 'locations', ['campus_id'], unique=False)
    op.create_index('ix_locations_campus_kind', 'locations', ['campus_id', 'kind'], unique=False)
    op.create_table('students',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('roll_number', sa.String(length=32), nullable=False),
    sa.Column('registration_number', sa.String(length=48), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('year_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('hostel_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('is_hosteller', sa.Boolean(), nullable=False),
    sa.Column('guardian_phone', sa.String(length=24), nullable=True),
    sa.Column('dues_amount', sa.Integer(), nullable=False),
    sa.Column('dues_paid', sa.Integer(), nullable=False),
    sa.Column('has_smartphone', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hostel_id'], ['hostels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['year_id'], ['years.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campus_id', 'roll_number', name='uq_student_campus_roll'),
    sa.UniqueConstraint('user_id', name='uq_student_user')
    )
    op.create_index(op.f('ix_students_campus_id'), 'students', ['campus_id'], unique=False)
    op.create_table('assets',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('OPERATIONAL', 'DEGRADED', 'UNDER_REPAIR', 'OUT_OF_SERVICE', 'RETIRED')", name='ck_state'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campus_id', 'code', name='uq_asset_campus_code')
    )
    op.create_index(op.f('ix_assets_campus_id'), 'assets', ['campus_id'], unique=False)
    op.create_index('ix_assets_campus_location', 'assets', ['campus_id', 'location_id'], unique=False)
    op.create_index(op.f('ix_assets_location_id'), 'assets', ['location_id'], unique=False)
    op.create_table('cases',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(length=24), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('requester_role', sa.String(length=32), nullable=False),
    sa.Column('requester_student_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('service_key', sa.String(length=48), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('subcategory', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('assigned_staff_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_step_key', sa.String(length=48), nullable=True),
    sa.Column('source_channel', sa.String(length=24), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('sla_minutes', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_state', sa.String(length=16), nullable=False),
    sa.Column('first_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('breached_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('at_risk_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('required_approvals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('state_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verification_state', sa.String(length=20), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('reopen_count', sa.Integer(), nullable=False),
    sa.Column('parent_case_id', sa.Integer(), nullable=True),
    sa.Column('duplicate_group_id', sa.String(length=64), nullable=True),
    sa.Column('dedupe_state', sa.String(length=16), nullable=False),
    sa.Column('dedupe_score', sa.Float(), nullable=True),
    sa.Column('client_ref', sa.String(length=80), nullable=True),
    sa.Column('captured_offline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("dedupe_state IN ('NONE', 'SUSPECTED', 'CONFIRMED')", name='ck_cases_dedupe_state'),
    sa.CheckConstraint("priority IN ('LOW', 'NORMAL', 'HIGH', 'CRITICAL', 'URGENT')", name='ck_cases_priority'),
    sa.CheckConstraint("sla_state IN ('NO_SLA', 'ON_TIME', 'AT_RISK', 'BREACHED', 'MET', 'MISSED')", name='ck_cases_sla_state'),
    sa.CheckConstraint("source_channel IN ('PWA', 'WEB_DESKTOP', 'KIOSK', 'ASSISTED_DESK', 'QR', 'PHONE', 'EMAIL', 'WALK_IN', 'AGENT', 'SYSTEM')", name='ck_cases_source_channel'),
    sa.CheckConstraint("status IN ('DRAFT', 'SUBMITTED', 'VALIDATING', 'ROUTED', 'ASSIGNED', 'IN_PROGRESS', 'WAITING_FOR_USER', 'WAITING_FOR_APPROVAL', 'ESCALATED', 'RESOLVED', 'VERIFICATION_REQUIRED', 'CLOSED', 'REOPENED', 'CANCELLED')", name='ck_status'),
    sa.CheckConstraint("verification_state IN ('NOT_REQUIRED', 'PENDING', 'VERIFIED', 'DISPUTED')", name='ck_cases_verification_state'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['staff.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_student_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campus_id', 'case_number', name='uq_case_campus_number')
    )
    op.create_index('ix_cases_asset', 'cases', ['asset_id', 'created_at'], unique=False)
    op.create_index('ix_cases_assignee', 'cases', ['assigned_staff_id', 'status'], unique=False)
    op.create_index(op.f('ix_cases_campus_id'), 'cases', ['campus_id'], unique=False)
    op.create_index(op.f('ix_cases_client_ref'), 'cases', ['client_ref'], unique=False)
    op.create_index('ix_cases_dept_queue', 'cases', ['campus_id', 'department_id', 'status'], unique=False)
    op.create_index('ix_cases_due', 'cases', ['campus_id', 'due_at'], unique=False)
    op.create_index(op.f('ix_cases_duplicate_group_id'), 'cases', ['duplicate_group_id'], unique=False)
    op.create_index('ix_cases_location', 'cases', ['location_id', 'created_at'], unique=False)
    op.create_index('ix_cases_queue', 'cases', ['campus_id', 'status', 'priority'], unique=False)
    op.create_index('ix_cases_requester', 'cases', ['requester_id', 'created_at'], unique=False)
    op.create_index('ix_cases_service', 'cases', ['campus_id', 'service_key', 'created_at'], unique=False)
    op.create_index(op.f('ix_cases_service_key'), 'cases', ['service_key'], unique=False)
    op.create_table('audit_logs',
    sa.Column('campus_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('actor_kind', sa.String(length=16), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('source_channel', sa.String(length=24), nullable=False),
    sa.Column('device_id', sa.String(length=80), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint("actor_kind IN ('USER', 'AGENT', 'SYSTEM', 'INTEGRATION')", name='ck_audit_logs_actor_kind'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_audit_logs_idempotency')
    )
    op.create_index('ix_audit_logs_campus_time', 'audit_logs', ['campus_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_case', 'audit_logs', ['case_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_type', 'audit_logs', ['event_type', 'created_at'], unique=False)
    op.create_table('case_approvals',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('step_key', sa.String(length=48), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('approver_role', sa.String(length=32), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("approver_role IN ('SUPER_ADMIN', 'ADMIN', 'WARDEN', 'DEPARTMENT_HEAD', 'STAFF', 'SECURITY', 'HELPDESK_OPERATOR', 'STUDENT')", name='ck_case_approvals_role'),
    sa.CheckConstraint("state IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'EXPIRED')", name='ck_state'),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_approvals_campus_id'), 'case_approvals', ['campus_id'], unique=False)
    op.create_index('ix_case_approvals_pending', 'case_approvals', ['campus_id', 'state', 'created_at'], unique=False)
    op.create_table('case_assignments',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=True),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.Column('assignment_type', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.String(length=240), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_assignments_campus_id'), 'case_assignments', ['campus_id'], unique=False)
    op.create_index('ix_case_assignments_case', 'case_assignments', ['case_id', 'is_active'], unique=False)
    op.create_table('case_attachments',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('filename', sa.String(length=240), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=400), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=240), nullable=True),
    sa.Column('client_ref', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_attachments_campus_id'), 'case_attachments', ['campus_id'], unique=False)
    op.create_index('ix_case_attachments_case', 'case_attachments', ['case_id', 'created_at'], unique=False)
    op.create_table('case_comments',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('author_role', sa.String(length=32), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('source_channel', sa.String(length=24), nullable=False),
    sa.Column('client_ref', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'client_ref', name='uq_case_comment_client_ref')
    )
    op.create_index(op.f('ix_case_comments_campus_id'), 'case_comments', ['campus_id'], unique=False)
    op.create_index('ix_case_comments_case', 'case_comments', ['case_id', 'created_at'], unique=False)
    op.create_table('case_events',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('actor_kind', sa.String(length=16), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=True),
    sa.Column('step_key', sa.String(length=48), nullable=True),
    sa.Column('source_channel', sa.String(length=24), nullable=False),
    sa.Column('device_id', sa.String(length=80), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', 'case_id', name='uq_case_event_idempotency')
    )
    op.create_index(op.f('ix_case_events_campus_id'), 'case_events', ['campus_id'], unique=False)
    op.create_index('ix_case_events_case', 'case_events', ['case_id', 'created_at'], unique=False)
    op.create_table('documents',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('serial_no', sa.String(length=32), nullable=False),
    sa.Column('verification_code', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('storage_path', sa.String(length=400), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('generated_by_id', sa.Integer(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoke_reason', sa.String(length=240), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('BONAFIDE_CERTIFICATE', 'FEE_RECEIPT', 'GATE_PASS', 'OTHER')", name='ck_documents_kind'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_no', name='uq_documents_serial'),
    sa.UniqueConstraint('verification_code', name='uq_documents_verification_code')
    )
    op.create_index(op.f('ix_documents_campus_id'), 'documents', ['campus_id'], unique=False)
    op.create_index('ix_documents_case', 'documents', ['case_id', 'created_at'], unique=False)
    op.create_table('gate_passes',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('pass_code', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_to', sa.DateTime(timezone=True), nullable=False),
    sa.Column('destination', sa.String(length=160), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('issued_by_id', sa.Integer(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=240), nullable=True),
    sa.Column('qr_payload', sa.String(length=160), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('ISSUED', 'PARTIALLY_USED', 'USED', 'EXPIRED', 'REVOKED')", name='ck_state'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pass_code', name='uq_gate_pass_code')
    )
    op.create_index(op.f('ix_gate_passes_campus_id'), 'gate_passes', ['campus_id'], unique=False)
    op.create_index('ix_gate_passes_campus_state', 'gate_passes', ['campus_id', 'state', 'valid_to'], unique=False)
    op.create_table('notice_actions',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=24), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action_type IN ('READ', 'ACKNOWLEDGE', 'SUBMIT_FORM', 'VIEW_DOCUMENT', 'REGISTER', 'OPEN_CASE', 'VIEW_TIMETABLE')", name='ck_notice_actions_type'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notice_id', 'user_id', 'action_type', name='uq_notice_action_unique')
    )
    op.create_index(op.f('ix_notice_actions_campus_id'), 'notice_actions', ['campus_id'], unique=False)
    op.create_table('notifications',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=600), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('action_label', sa.String(length=80), nullable=True),
    sa.Column('action_type', sa.String(length=40), nullable=True),
    sa.Column('action_target', sa.String(length=120), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('notice_id', sa.Integer(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('CASE_UPDATE', 'APPROVAL', 'CERTIFICATE_READY', 'LEAVE_STATUS', 'GATE_PASS', 'TIMETABLE', 'NOTICE', 'URGENT_ANNOUNCEMENT', 'SLA_ALERT', 'SYSTEM', 'MESS', 'ACADEMIC', 'HOSTEL')", name='ck_notifications_category'),
    sa.CheckConstraint("priority IN ('LOW', 'NORMAL', 'HIGH', 'CRITICAL', 'URGENT')", name='ck_notifications_priority'),
    sa.CheckConstraint("state IN ('SENT', 'DELIVERED', 'READ', 'ACTIONED', 'FAILED')", name='ck_notifications_state'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_campus_id'), 'notifications', ['campus_id'], unique=False)
    op.create_index(op.f('ix_notifications_dedupe_key'), 'notifications', ['dedupe_key'], unique=False)
    op.create_index('ix_notifications_user_category', 'notifications', ['user_id', 'category', 'created_at'], unique=False)
    op.create_index('ix_notifications_user_state', 'notifications', ['user_id', 'state', 'created_at'], unique=False)
    op.create_table('gate_logs',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('gate_pass_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('gate_location_id', sa.Integer(), nullable=True),
    sa.Column('logged_by_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(length=80), nullable=True),
    sa.Column('source_channel', sa.String(length=24), nullable=False),
    sa.Column('offline_captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('client_ref', sa.String(length=80), nullable=True),
    sa.Column('note', sa.String(length=240), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direction IN ('ENTRY', 'EXIT')", name='ck_gate_logs_direction'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gate_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gate_pass_id'], ['gate_passes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['logged_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_ref', name='uq_gate_logs_client_ref')
    )
    op.create_index(op.f('ix_gate_logs_campus_id'), 'gate_logs', ['campus_id'], unique=False)
    op.create_index('ix_gate_logs_campus_time', 'gate_logs', ['campus_id', 'occurred_at'], unique=False)
    op.create_index('ix_gate_logs_student', 'gate_logs', ['student_id', 'occurred_at'], unique=False)
    op.create_table('notification_events',
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.String(length=400), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint("channel IN ('IN_APP', 'PUSH')", name='ck_notification_events_channel'),
    sa.CheckConstraint("state IN ('SENT', 'DELIVERED', 'READ', 'ACTIONED', 'FAILED')", name='ck_notification_events_state'),
    sa.ForeignKeyConstraint(['campus_id'], ['campuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_events_campus_id'), 'notification_events', ['campus_id'], unique=False)
    op.create_index('ix_notification_events_notification', 'notification_events', ['notification_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_events_notification', table_name='notification_events')
    op.drop_index(op.f('ix_notification_events_campus_id'), table_name='notification_events')
    op.drop_table('notification_events')
    op.drop_index('ix_gate_logs_student', table_name='gate_logs')
    op.drop_index('ix_gate_logs_campus_time', table_name='gate_logs')
    op.drop_index(op.f('ix_gate_logs_campus_id'), table_name='gate_logs')
    op.drop_table('gate_logs')
    op.drop_index('ix_notifications_user_state', table_name='notifications')
    op.drop_index('ix_notifications_user_category', table_name='notifications')
    op.drop_index(op.f('ix_notifications_dedupe_key'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_campus_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notice_actions_campus_id'), table_name='notice_actions')
    op.drop_table('notice_actions')
    op.drop_index('ix_gate_passes_campus_state', table_name='gate_passes')
    op.drop_index(op.f('ix_gate_passes_campus_id'), table_name='gate_passes')
    op.drop_table('gate_passes')
    op.drop_index('ix_documents_case', table_name='documents')
    op.drop_index(op.f('ix_documents_campus_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_case_events_case', table_name='case_events')
    op.drop_index(op.f('ix_case_events_campus_id'), table_name='case_events')
    op.drop_table('case_events')
    op.drop_index('ix_case_comments_case', table_name='case_comments')
    op.drop_index(op.f('ix_case_comments_campus_id'), table_name='case_comments')
    op.drop_table('case_comments')
    op.drop_index('ix_case_attachments_case', table_name='case_attachments')
    op.drop_index(op.f('ix_case_attachments_campus_id'), table_name='case_attachments')
    op.drop_table('case_attachments')
    op.drop_index('ix_case_assignments_case', table_name='case_assignments')
    op.drop_index(op.f('ix_case_assignments_campus_id'), table_name='case_assignments')
    op.drop_table('case_assignments')
    op.drop_index('ix_case_approvals_pending', table_name='case_approvals')
    op.drop_index(op.f('ix_case_approvals_campus_id'), table_name='case_approvals')
    op.drop_table('case_approvals')
    op.drop_index('ix_audit_logs_type', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_case', table_name='audit_logs')
    op.drop_index('ix_audit_logs_campus_time', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_cases_service_key'), table_name='cases')
    op.drop_index('ix_cases_service', table_name='cases')
    op.drop_index('ix_cases_requester', table_name='cases')
    op.drop_index('ix_cases_queue', table_name='cases')
    op.drop_index('ix_cases_location', table_name='cases')
    op.drop_index(op.f('ix_cases_duplicate_group_id'), table_name='cases')
    op.drop_index('ix_cases_due', table_name='cases')
    op.drop_index('ix_cases_dept_queue', table_name='cases')
    op.drop_index(op.f('ix_cases_client_ref'), table_name='cases')
    op.drop_index(op.f('ix_cases_campus_id'), table_name='cases')
    op.drop_index('ix_cases_assignee', table_name='cases')
    op.drop_index('ix_cases_asset', table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_assets_location_id'), table_name='assets')
    op.drop_index('ix_assets_campus_location', table_name='assets')
    op.drop_index(op.f('ix_assets_campus_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_students_campus_id'), table_name='students')
    op.drop_table('students')
    op.drop_index('ix_locations_campus_kind', table_name='locations')
    op.drop_index(op.f('ix_locations_campus_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_rooms_hostel_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_campus_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_block_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index('ix_notice_targets_notice', table_name='notice_targets')
    op.drop_index('ix_notice_targets_lookup', table_name='notice_targets')
    op.drop_table('notice_targets')
    op.drop_index(op.f('ix_notice_shares_campus_id'), table_name='notice_shares')
    op.drop_table('notice_shares')
    op.drop_index('ix_notice_reads_user', table_name='notice_reads')
    op.drop_index('ix_notice_reads_notice_state', table_name='notice_reads')
    op.drop_index(op.f('ix_notice_reads_campus_id'), table_name='notice_reads')
    op.drop_table('notice_reads')
    op.drop_index(op.f('ix_blocks_hostel_id'), table_name='blocks')
    op.drop_index(op.f('ix_blocks_campus_id'), table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_workflow_steps_workflow_id'), table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index('ix_sync_operations_user_device', table_name='sync_operations')
    op.drop_index('ix_sync_operations_status', table_name='sync_operations')
    op.drop_index(op.f('ix_sync_operations_campus_id'), table_name='sync_operations')
    op.drop_table('sync_operations')
    op.drop_index(op.f('ix_staff_department_id'), table_name='staff')
    op.drop_index(op.f('ix_staff_campus_id'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_services_campus_id'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_notification_preferences_campus_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index('ix_notices_campus_status', table_name='notices')
    op.drop_index(op.f('ix_notices_campus_id'), table_name='notices')
    op.drop_table('notices')
    op.drop_index(op.f('ix_hostels_campus_id'), table_name='hostels')
    op.drop_table('hostels')
    op.drop_index(op.f('ix_devices_campus_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_branches_department_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_campus_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_years_campus_id'), table_name='years')
    op.drop_table('years')
    op.drop_index(op.f('ix_workflows_campus_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index('ix_users_campus_role', table_name='users')
    op.drop_index(op.f('ix_users_campus_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sla_rules_campus_id'), table_name='sla_rules')
    op.drop_table('sla_rules')
    op.drop_table('role_permissions')
    op.drop_index('ix_policies_campus_service', table_name='policies')
    op.drop_index(op.f('ix_policies_campus_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_departments_campus_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_batches_campus_id'), table_name='batches')
    op.drop_table('batches')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('campuses')
    # ### end Alembic commands ###
